export const GET_TRENDING_MOVIES_SUCCESS = "GET_TRENDING_MOVIES_SUCCESS";
export const GET_MOVIES_FAILURE = "GET_MOVIES_FAILURE";
export const GET_ACTION_MOVIES_SUCCESS = "GET_ACTION_MOVIES_SUCCESS";
export const GET_SINGLE_MOVIE = "GET_SINGLE_MOVIE";
export const GET_SIMILAR_MOVIES = "GET_SIMILAR_MOVIES";
export const GET_MOVIE_VIDEO = "GET_MOVIE_VIDEO";
export const GET_SEARCHED_MOVIES = "GET_SEARCHED_MOVIES";
