export const GET_TRENDING_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAILURE = "GET_MOVIES_FAILURE";
export const SET_LOADING = "SET_LOADING";
export const GET_ACTION_MOVIES_SUCCESS = "GET_ACTION_MOVIES_SUCCESS";
export const GET_SINGLE_MOVIE = "GET_SINGLE_MOVIE";
